version: '3.8'

services:
  m347-kn04a-db:
    image: mariadb:latest
    container_name: m347-kn04a-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
     - m347-kn04a-net
        

  m347-kn04a-web:
    build: .
    container_name: m347-kn04a-web
    ports:
      - "80:80"
    networks:
     - m347-kn04a-net
       

networks:
  m347-kn04a-net:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16
          ip_range: 172.10.5.0/24
          gateway: 172.10.5.254